package taskspec

import (
	"bufio"
	"os"
	"strings"
	"testing"
)

// TestAbnfGenSamples tests parser with samples generated by abnfgen from the grammar file.
// This test expects a file at testdata/abnfgen_samples.txt with one sample per line.
// The file is expected to be generated by an external process (e.g., in CI).
func TestAbnfGenSamples(t *testing.T) {
	// Check if abnfgen samples file exists
	samplesFile := "testdata/abnfgen_samples.txt"
	if _, err := os.Stat(samplesFile); os.IsNotExist(err) {
		t.Skip("Skipping abnfgen test: testdata/abnfgen_samples.txt not found. Run abnfgen to generate samples first.")
		return
	}

	// Open and read the samples file
	file, err := os.Open(samplesFile)
	if err != nil {
		t.Fatalf("Failed to open abnfgen samples file: %v", err)
	}
	defer file.Close()

	parser := NewParser()
	scanner := bufio.NewScanner(file)
	lineNum := 0
	successCount := 0
	failCount := 0
	panicCount := 0

	for scanner.Scan() {
		lineNum++
		sample := scanner.Text()

		// Skip empty lines
		if strings.TrimSpace(sample) == "" {
			continue
		}

		// Test that the parser doesn't panic
		func() {
			defer func() {
				if r := recover(); r != nil {
					panicCount++
					t.Errorf("Line %d: Parser panicked on abnfgen sample %q: %v", lineNum, sample, r)
				}
			}()

			// Try to parse the sample
			task, err := parser.Parse(sample)
			if err != nil {
				failCount++
				// We don't fail the test on parse errors, just count them
				// The grammar might generate valid ABNF that doesn't make semantic sense
				t.Logf("Line %d: Failed to parse abnfgen sample %q: %v", lineNum, sample, err)
			} else if task != nil {
				successCount++
			}
		}()
	}

	if err := scanner.Err(); err != nil {
		t.Fatalf("Error reading abnfgen samples file: %v", err)
	}

	// Log statistics
	t.Logf("Abnfgen test statistics:")
	t.Logf("  Total samples: %d", lineNum)
	t.Logf("  Successfully parsed: %d", successCount)
	t.Logf("  Parse failures: %d", failCount)
	t.Logf("  Panics: %d", panicCount)

	// The test fails only if there were panics
	if panicCount > 0 {
		t.Errorf("Parser panicked %d times on abnfgen samples", panicCount)
	}
}
